# Generated by Django 4.0.6 on 2022-07-14 07:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('name', models.CharField(max_length=200, verbose_name='Award Name')),
                ('description', models.TextField(verbose_name='Award Description')),
            ],
            options={
                'verbose_name_plural': 'Awards',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='AwardUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='award.award')),
            ],
            options={
                'verbose_name_plural': 'Awards - Users',
            },
        ),
    ]
