version: "3.8"

services:
  web:
    build: .
    container_name: django
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    env_file:
      - ./config/.env
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports: 
    - 127.0.0.1:6379:6379
    volumes:
      - .redis.conf:/usr/src/app
