# Generated by Django 4.0.6 on 2022-07-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trivia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trivia",
            name="option_3",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
